# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
    ]
