# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_name', '0003_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.NullBooleanField(default=True),
        ),
    ]
