# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_name', '0004_auto_20190204_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
